@startuml
class Solution41 {
    -List<String> nameList
    -List<String> sortedList
    -String fileLocation

    +getFileData(fileLocation)
    +alphabeticSorter(nameList)
    +outputFileData(sortedList)
}
@enduml